/**
 * Broadcast.java
 *
 * Created on Oct 14, 2010, 4:47:24 PM
 *
 * @author pquiring
 *
 * This class implements Broadcasting a pre-recorded message to a list of phone numbers and/or taking surveys.
 *
 * NOTE : Please only broadcast to your own customers.  Laws in some countries/states may prohibit contacting random individuals.
 *
 */

import javaforce.*;
import javaforce.voip.*;

import java.io.*;
import java.net.*;
import java.util.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.*;

public class Broadcast extends javax.swing.JFrame implements SIPClientInterface, RTPInterface {

  public final String version = "0.17";

  /** Creates new form Broadcast */
  public Broadcast() {
    SQL.initOnce();
    initComponents();
    setPosition();
    loadHelp();
    setTitle("jfBroadcast/" + version);
    JFLog.init("broadcast.log", true);
    loadSetup();
    updateAvailableLists();
    new Thread() {
      @Override
      public void run() {
        createDatabase();
        if (check_update.isSelected()) checkVersion();
      }
    }.start();
    idx = 0;
    buttonGroup1.add(single);
    buttonGroup1.add(multi);
    buttonGroup1.add(terminate);
    buttonGroup1.add(gotouser);
    buttonGroup1.add(cont);
    buttonGroup1.add(gotoidx);
    buttonGroup1.add(xfer);
    loadQuestion();
    processArgs();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    listView = new javax.swing.JTable();
    start = new javax.swing.JButton();
    status = new javax.swing.JLabel();
    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel2 = new javax.swing.JPanel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    sip_user = new javax.swing.JTextField();
    sip_auth = new javax.swing.JTextField();
    sip_host = new javax.swing.JTextField();
    sip_pass = new javax.swing.JTextField();
    jPanel3 = new javax.swing.JPanel();
    create_list = new javax.swing.JButton();
    list_name = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    selected_list = new javax.swing.JComboBox();
    reset_list = new javax.swing.JButton();
    delete_list = new javax.swing.JButton();
    export_list = new javax.swing.JButton();
    import_list = new javax.swing.JButton();
    fix_list = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    greeting_threshold = new javax.swing.JTextField();
    silence_threshold = new javax.swing.JTextField();
    silence_duration = new javax.swing.JTextField();
    disable_detect = new javax.swing.JCheckBox();
    jPanel7 = new javax.swing.JPanel();
    jLabel13 = new javax.swing.JLabel();
    enable_g729a = new javax.swing.JCheckBox();
    enable_reinvites = new javax.swing.JCheckBox();
    jLabel6 = new javax.swing.JLabel();
    maxRingTime = new javax.swing.JSpinner();
    enable_g711u = new javax.swing.JCheckBox();
    enable_g711a = new javax.swing.JCheckBox();
    number_lines = new javax.swing.JSpinner();
    jLabel24 = new javax.swing.JLabel();
    jLabel23 = new javax.swing.JLabel();
    delay = new javax.swing.JSpinner();
    check_update = new javax.swing.JCheckBox();
    maxAttempts = new javax.swing.JSpinner();
    jPanel8 = new javax.swing.JPanel();
    xfer_number = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    xfer_digit = new javax.swing.JTextField();
    enable_xfer = new javax.swing.JCheckBox();
    jPanel5 = new javax.swing.JPanel();
    enable = new javax.swing.JCheckBox();
    wav_filename = new javax.swing.JTextField();
    select_file = new javax.swing.JButton();
    next_msg = new javax.swing.JButton();
    prev_msg = new javax.swing.JButton();
    title = new javax.swing.JLabel();
    single = new javax.swing.JRadioButton();
    count = new javax.swing.JComboBox();
    multi = new javax.swing.JRadioButton();
    terminate = new javax.swing.JRadioButton();
    gotouser = new javax.swing.JRadioButton();
    goto_1 = new javax.swing.JTextField();
    goto_2 = new javax.swing.JTextField();
    goto_3 = new javax.swing.JTextField();
    goto_4 = new javax.swing.JTextField();
    goto_5 = new javax.swing.JTextField();
    goto_6 = new javax.swing.JTextField();
    goto_7 = new javax.swing.JTextField();
    goto_8 = new javax.swing.JTextField();
    goto_9 = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    jLabel20 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();
    cont = new javax.swing.JRadioButton();
    gotoidx = new javax.swing.JRadioButton();
    gotoidxnum = new javax.swing.JTextField();
    jLabel22 = new javax.swing.JLabel();
    msg_idx = new javax.swing.JSlider();
    xfer = new javax.swing.JRadioButton();
    jPanel6 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    help = new javax.swing.JTextArea();
    save_setup = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("jfBroadcast");
    setResizable(false);

    jLabel1.setText("Broadcast a message to a list of phone numbers or take a survey.");

    listView.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Number", "Status", "Attempts", "Survey"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    listView.setEnabled(false);
    jScrollPane1.setViewportView(listView);

    start.setText("Start!");
    start.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        startActionPerformed(evt);
      }
    });

    status.setText("Status:OK");

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("SIP Details"));

    jLabel9.setText("user");

    jLabel10.setText("auth");

    jLabel11.setText("host");

    jLabel12.setText("pass");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sip_user, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel10)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sip_auth, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel11)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sip_host, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel12)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sip_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9)
          .addComponent(sip_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel10)
          .addComponent(sip_auth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel11)
          .addComponent(sip_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel12)
          .addComponent(sip_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    jTabbedPane1.addTab("SIP", jPanel2);

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lists"));

    create_list.setText("Create List...");
    create_list.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        create_listActionPerformed(evt);
      }
    });

    list_name.setText("default");

    jLabel5.setText("Select List:");

    selected_list.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        selected_listItemStateChanged(evt);
      }
    });

    reset_list.setText("Reset List...");
    reset_list.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        reset_listActionPerformed(evt);
      }
    });

    delete_list.setText("Delete List...");
    delete_list.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        delete_listActionPerformed(evt);
      }
    });

    export_list.setText("Export List...");
    export_list.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        export_listActionPerformed(evt);
      }
    });

    import_list.setText("Import List...");
    import_list.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        import_listActionPerformed(evt);
      }
    });

    fix_list.setText("Fix List...");
    fix_list.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fix_listActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(import_list)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(export_list))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                .addComponent(create_list)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list_name))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selected_list, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(reset_list)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(delete_list)
            .addGap(6, 6, 6)
            .addComponent(fix_list)))
        .addContainerGap(129, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(list_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(create_list))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(selected_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(reset_list)
          .addComponent(delete_list)
          .addComponent(fix_list))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(import_list)
          .addComponent(export_list))
        .addContainerGap(268, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Lists", jPanel3);

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Human/Machine Detection Options"));

    jLabel2.setText("Greeting Detection Threshold:");
    jLabel2.setToolTipText("100-32000 (default = 1000)");

    jLabel3.setText("Silence Detection Threshold:");
    jLabel3.setToolTipText("100-32000 (default = 1000)");

    jLabel4.setText("Silence Duration (ms):");
    jLabel4.setToolTipText("100-5000 (default = 1000)");

    greeting_threshold.setText("1000");
    greeting_threshold.setToolTipText("100-32000 (default = 1000)");

    silence_threshold.setText("1000");
    silence_threshold.setToolTipText("100-32000 (default = 1000)");

    silence_duration.setText("100");
    silence_duration.setToolTipText("100-5000 (default = 1000)");

    disable_detect.setText("Disable human/machine detection");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(greeting_threshold, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3)
              .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(silence_threshold)
              .addComponent(silence_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(disable_detect)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(disable_detect)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(greeting_threshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(silence_threshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(7, 7, 7)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(silence_duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("General Options"));

    jLabel13.setText("Delay (ms) :");
    jLabel13.setToolTipText("100-10000");

    enable_g729a.setSelected(true);
    enable_g729a.setText("Enable g729a codec");

    enable_reinvites.setText("Enable reinvites");

    jLabel6.setText("Number of Lines:");
    jLabel6.setToolTipText("Number of concurrent calls.");

    maxRingTime.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        maxRingTimeStateChanged(evt);
      }
    });

    enable_g711u.setSelected(true);
    enable_g711u.setText("Enable g711u codec");

    enable_g711a.setText("Enable g711a codec");

    number_lines.setValue(4);
    number_lines.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        number_linesStateChanged(evt);
      }
    });

    jLabel24.setText("Max Attempts:");
    jLabel24.setToolTipText("Max attempts to call each number.");

    jLabel23.setText("Max Ring Time:");
    jLabel23.setToolTipText("Max ring time in seconds.");

    delay.setToolTipText("100-10000");
    delay.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        delayStateChanged(evt);
      }
    });

    check_update.setSelected(true);
    check_update.setText("Check for update on startup");

    maxAttempts.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        maxAttemptsStateChanged(evt);
      }
    });

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
      jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel7Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
              .addComponent(jLabel24)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(maxAttempts))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
              .addComponent(jLabel23)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(maxRingTime))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
              .addComponent(jLabel13)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(delay))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
              .addComponent(jLabel6)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(number_lines, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(enable_g711a)
          .addComponent(enable_g711u)
          .addComponent(enable_g729a)
          .addComponent(check_update)
          .addComponent(enable_reinvites))
        .addContainerGap())
    );
    jPanel7Layout.setVerticalGroup(
      jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel7Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(number_lines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel13)
          .addComponent(delay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(7, 7, 7)
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel23)
          .addComponent(maxRingTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel24)
          .addComponent(maxAttempts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(enable_g729a)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(enable_g711u)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(enable_g711a)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(enable_reinvites)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(check_update)
        .addContainerGap())
    );

    jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Transfer Option"));

    jLabel7.setText("Transfer destination =");

    xfer_digit.setText("0");

    enable_xfer.setText("Enable transfer : Digit =");

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
      jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel8Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(enable_xfer)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(xfer_digit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(xfer_number, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel8Layout.setVerticalGroup(
      jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel8Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(enable_xfer)
          .addComponent(xfer_digit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(xfer_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7))
        .addContainerGap())
    );

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Options", jPanel4);

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Messages / Questions"));

    enable.setText("Enable : WAV=");

    wav_filename.setText("filename.wav");

    select_file.setText("...");
    select_file.setToolTipText("Select File...");
    select_file.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        select_fileActionPerformed(evt);
      }
    });

    next_msg.setText(">");
    next_msg.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        next_msgActionPerformed(evt);
      }
    });

    prev_msg.setText("<");
    prev_msg.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        prev_msgActionPerformed(evt);
      }
    });

    title.setText("#1/99");

    single.setText("Single digit response : allowed responses =");

    count.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "1-2", "1-3", "1-4", "1-5", "1-6", "1-7", "1-8", "1-9" }));

    multi.setText("Long response (user ends input with # or after 5 sec pause) (continues to next message)");

    terminate.setText("Terminate call after this message");

    gotouser.setText("Goto message from user input (1-99)");
    gotouser.setToolTipText("Goto question based on digit pressed.");

    goto_1.setText("0");
    goto_1.setToolTipText("1");

    goto_2.setText("0");
    goto_2.setToolTipText("2");

    goto_3.setText("0");
    goto_3.setToolTipText("3");

    goto_4.setText("0");
    goto_4.setToolTipText("4");

    goto_5.setText("0");
    goto_5.setToolTipText("5");

    goto_6.setText("0");
    goto_6.setToolTipText("6");

    goto_7.setText("0");
    goto_7.setToolTipText("7");

    goto_8.setText("0");
    goto_8.setToolTipText("8");

    goto_9.setText("0");
    goto_9.setToolTipText("9");

    jLabel8.setText("1:");

    jLabel14.setText("3:");

    jLabel15.setText("2:");

    jLabel16.setText("4:");

    jLabel17.setText("5:");

    jLabel18.setText("7:");

    jLabel19.setText("6:");

    jLabel20.setText("9:");

    jLabel21.setText("8:");

    cont.setSelected(true);
    cont.setText("Continue to next message");

    gotoidx.setText("Goto message after this message (1-99)");

    gotoidxnum.setText("0");

    jLabel22.setText("(continues to next message)");

    msg_idx.setMaximum(98);
    msg_idx.setValue(0);
    msg_idx.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        msg_idxStateChanged(evt);
      }
    });

    xfer.setText("Transfer call after message");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(multi)
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(single)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel22))
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(gotoidx)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(gotoidxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(enable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wav_filename, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
              .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(cont)
                  .addComponent(terminate))
                .addGap(249, 249, 249)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(msg_idx, 0, 0, Short.MAX_VALUE)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(select_file)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prev_msg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(next_msg))))
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(gotouser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(xfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel8)
            .addGap(2, 2, 2)
            .addComponent(goto_1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel15)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(goto_2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel14)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(goto_3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel16)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(goto_4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel17)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(goto_5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel19)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(goto_6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel18)
            .addGap(6, 6, 6)
            .addComponent(goto_7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel21)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(goto_8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel20)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(goto_9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(enable)
          .addComponent(wav_filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(next_msg)
          .addComponent(prev_msg)
          .addComponent(title)
          .addComponent(select_file))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(cont)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(terminate)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(single)
              .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel22)))
          .addComponent(msg_idx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(multi)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(gotoidx)
          .addComponent(gotoidxnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(gotouser)
          .addComponent(goto_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8)
          .addComponent(jLabel15)
          .addComponent(goto_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(goto_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(goto_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel14)
          .addComponent(jLabel16)
          .addComponent(jLabel17)
          .addComponent(goto_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(goto_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(goto_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(goto_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel18)
          .addComponent(jLabel19)
          .addComponent(jLabel21)
          .addComponent(jLabel20)
          .addComponent(goto_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(xfer)
        .addContainerGap(154, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Messages / Questions", jPanel5);

    help.setColumns(20);
    help.setEditable(false);
    help.setRows(5);
    jScrollPane2.setViewportView(help);

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Help", jPanel6);

    save_setup.setText("Save Setup");
    save_setup.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        save_setupActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
          .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
            .addComponent(save_setup))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addComponent(start)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(save_setup))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(start)
          .addComponent(status))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
      if (state == states.CALLING) {
        stopCalling();
        return;
      }
      if (state == states.STOPPING) {
        if (JF.showConfirm("Warning", "Are you sure you want to force stop?")) {
          forceStopCalling();
        }
        return;
      }
      callingThread = new Thread() {
        @Override
        public void run() {
          startCalling();
        }
      };
      callingThread.start();
    }//GEN-LAST:event_startActionPerformed

    private void save_setupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_setupActionPerformed
      saveSetup();
    }//GEN-LAST:event_save_setupActionPerformed

  private void msg_idxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_msg_idxStateChanged
    gotoQuestion(msg_idx.getValue());
  }//GEN-LAST:event_msg_idxStateChanged

  private void prev_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_msgActionPerformed
    prevQuestion();
  }//GEN-LAST:event_prev_msgActionPerformed

  private void next_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_msgActionPerformed
    nextQuestion();
  }//GEN-LAST:event_next_msgActionPerformed

  private void select_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_fileActionPerformed
    selectFile();
  }//GEN-LAST:event_select_fileActionPerformed

  private void maxAttemptsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maxAttemptsStateChanged
    validateOptions();
  }//GEN-LAST:event_maxAttemptsStateChanged

  private void maxRingTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maxRingTimeStateChanged
    validateOptions();
  }//GEN-LAST:event_maxRingTimeStateChanged

  private void number_linesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_number_linesStateChanged
    validateOptions();
  }//GEN-LAST:event_number_linesStateChanged

  private void delayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_delayStateChanged
    validateOptions();
  }//GEN-LAST:event_delayStateChanged

  private void fix_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fix_listActionPerformed
    fixList(false);
  }//GEN-LAST:event_fix_listActionPerformed

  private void import_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_import_listActionPerformed
    importList();
  }//GEN-LAST:event_import_listActionPerformed

  private void export_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export_listActionPerformed
    exportList();
  }//GEN-LAST:event_export_listActionPerformed

  private void delete_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_listActionPerformed
    deleteList();
  }//GEN-LAST:event_delete_listActionPerformed

  private void reset_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_listActionPerformed
    resetList();
  }//GEN-LAST:event_reset_listActionPerformed

  private void selected_listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selected_listItemStateChanged
    updateList();
  }//GEN-LAST:event_selected_listItemStateChanged

  private void create_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_listActionPerformed
    createList();
  }//GEN-LAST:event_create_listActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    Broadcast.args = args;
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Broadcast().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JCheckBox check_update;
  private javax.swing.JRadioButton cont;
  private javax.swing.JComboBox count;
  private javax.swing.JButton create_list;
  private javax.swing.JSpinner delay;
  private javax.swing.JButton delete_list;
  private javax.swing.JCheckBox disable_detect;
  private javax.swing.JCheckBox enable;
  private javax.swing.JCheckBox enable_g711a;
  private javax.swing.JCheckBox enable_g711u;
  private javax.swing.JCheckBox enable_g729a;
  private javax.swing.JCheckBox enable_reinvites;
  private javax.swing.JCheckBox enable_xfer;
  private javax.swing.JButton export_list;
  private javax.swing.JButton fix_list;
  private javax.swing.JTextField goto_1;
  private javax.swing.JTextField goto_2;
  private javax.swing.JTextField goto_3;
  private javax.swing.JTextField goto_4;
  private javax.swing.JTextField goto_5;
  private javax.swing.JTextField goto_6;
  private javax.swing.JTextField goto_7;
  private javax.swing.JTextField goto_8;
  private javax.swing.JTextField goto_9;
  private javax.swing.JRadioButton gotoidx;
  private javax.swing.JTextField gotoidxnum;
  private javax.swing.JRadioButton gotouser;
  private javax.swing.JTextField greeting_threshold;
  private javax.swing.JTextArea help;
  private javax.swing.JButton import_list;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel22;
  private javax.swing.JLabel jLabel23;
  private javax.swing.JLabel jLabel24;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JTable listView;
  private javax.swing.JTextField list_name;
  private javax.swing.JSpinner maxAttempts;
  private javax.swing.JSpinner maxRingTime;
  private javax.swing.JSlider msg_idx;
  private javax.swing.JRadioButton multi;
  private javax.swing.JButton next_msg;
  private javax.swing.JSpinner number_lines;
  private javax.swing.JButton prev_msg;
  private javax.swing.JButton reset_list;
  private javax.swing.JButton save_setup;
  private javax.swing.JButton select_file;
  private javax.swing.JComboBox selected_list;
  private javax.swing.JTextField silence_duration;
  private javax.swing.JTextField silence_threshold;
  private javax.swing.JRadioButton single;
  private javax.swing.JTextField sip_auth;
  private javax.swing.JTextField sip_host;
  private javax.swing.JTextField sip_pass;
  private javax.swing.JTextField sip_user;
  private javax.swing.JButton start;
  private javax.swing.JLabel status;
  private javax.swing.JRadioButton terminate;
  private javax.swing.JLabel title;
  private javax.swing.JTextField wav_filename;
  private javax.swing.JRadioButton xfer;
  private javax.swing.JTextField xfer_digit;
  private javax.swing.JTextField xfer_number;
  // End of variables declaration//GEN-END:variables

  //global data
  enum states { STOPPED, CALLING, STOPPING};
  states state = states.STOPPED;
  Thread callingThread;
  int lineCount;
  SIPClient sip;
  Lines lines[];
  boolean registered;
  short silence[] = new short[160];
  short tmp[] = new short[160];
  Wav wav[];
  SQL psql;  //persistant sql connection
  String dbname = "broadcast";
  String listid;
  volatile boolean processing = false;
  int skipCount;
  int maxquietcount;
  static String args[];
  static class update {
    public String number, status, survey;
    public update(String number, String status, String survey) {
      this.number = number;
      this.status = status;
      this.survey = survey;
    }
  }
  Vector<update> updateList = new Vector<update>();
  final static int NUMQUESTIONS = 99;
  //actions
  final static int A_CONT = 0;
  final static int A_TERMINATE = 4;
  final static int A_SINGLE = 1;
  final static int A_MULTI = 2;
  final static int A_GOTOUSER = 3;
  final static int A_GOTOIDX = 5;
  final static int A_XFER = 6;

  public void createDatabase() {
    File file = new File("database");
    if (file.exists()) return;  //already exists
    JFTask task = new JFTask() {
      public boolean work() {
        this.setTitle("Creating database...");
        this.setLabel("Creating database...");
        this.setProgress(50);
        SQL sql = new SQL();
        if (!sql.init("create=true")) {
          this.setLabel("Database create failed : SQL connection failed");
          return false;
        }
        if (!sql.execute("create table lists (id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) primary key, name varchar(37) not null unique)")) {
          this.setLabel("Database create failed : Create Table failed (already created?)");
          return false;
        }
        if (!sql.execute("create table listdata (id int not null, number varchar(32) not null, status varchar(32) default 'new' not null, attempts int default 0 not null, survey varchar(64), unique(number, id))")) {
          this.setLabel("Database create failed : Create Table failed (already created?)");
          return false;
        }
        this.setProgress(100);
        this.setLabel("Database created succesfully");
        return true;
      }
    };
    ProgressDialog pd = new ProgressDialog(this, true, task);
    pd.setVisible(true);
  }

  public void setStatus(String str) {
    status.setText("Status:" + str);
  }

  public String safe(String str) {
    char strin[] = str.toCharArray();
    char strout[] = new char[str.length()];
    for(int a=0;a<strin.length;a++) {
      if ((Character.toLowerCase(strin[a]) >= 'a') && (Character.toLowerCase(strin[a]) <= 'z')) {
        strout[a] = strin[a];
        continue;
      }
      if ((strin[a] >= '0') && (strin[a] <= '9')) {
        strout[a] = strin[a];
        continue;
      }
      strout[a] = '_';
    }
    return new String(strout);
  }

  public void createList() {
    String safe = safe(list_name.getText());
    if (safe.length() == 0) return;
    SQL sql = new SQL();
    if (!sql.init()) {
      setStatus("SQL connection failed");
      return;
    }
    if (!sql.execute("insert into lists values (default, '" + safe + "')")) {
      setStatus("Insert failed (already created?)");
      return;
    }
    setStatus("OK:CreateTable:" + safe);
    updateAvailableLists();
  }

  public void deleteList() {
    String sel = (String)selected_list.getSelectedItem();
    if (sel == null || sel.length() == 0) return;
    if (JOptionPane.showConfirmDialog(null, "Delete List:" + sel + "?", "Sure?", JOptionPane.OK_CANCEL_OPTION) != JOptionPane.OK_OPTION) return;
    SQL sql = new SQL();
    if (!sql.init()) {
      setStatus("SQL connection failed");
      return;
    }
    if (!sql.execute("delete from listdata where id=(select id from lists where name='"+sel+"')")) {
      setStatus("delete from lists failed(1)");
      return;
    }
    if (!sql.execute("delete from lists where name='"+sel+"'")) {
      setStatus("delete from lists failed(2)");
      return;
    }
    setStatus("OK:DeleteList:"+sel);
    updateAvailableLists();
  }

  public void resetList() {
    String sel = (String)selected_list.getSelectedItem();
    if (sel == null || sel.length() == 0) return;
    if (JOptionPane.showConfirmDialog(null, "Reset List:" + sel + "?", "Sure?", JOptionPane.OK_CANCEL_OPTION) != JOptionPane.OK_OPTION) return;
    SQL sql = new SQL();
    if (!sql.init()) {
      setStatus("SQL connection failed");
      return;
    }
    if (!sql.execute("update listdata set status='new', attempts = 0, survey = '' where id=(select id from lists where name='" + sel + "')")) {
      setStatus("update failed");
      return;
    }
    setStatus("OK:ResetList:"+sel);
    updateList();
  }

  public void fixList(boolean quite) {
    String sel = (String)selected_list.getSelectedItem();
    if (sel == null || sel.length() == 0) return;
    if (!quite) {
      if (JOptionPane.showConfirmDialog(null, "Fix List:" + sel + "?", "Sure?", JOptionPane.OK_CANCEL_OPTION) != JOptionPane.OK_OPTION) return;
    }
    SQL sql = new SQL();
    if (!sql.init()) {
      setStatus("SQL connection failed");
      return;
    }
    if (!sql.execute("update listdata set status='new' where status='calling' and id=(select id from lists where name='" + sel + "')")) {
      setStatus("update failed");
      return;
    }
    if (!quite) {
      setStatus("OK:FixList:"+sel);
    }
    updateList();
  }

  public final void updateAvailableLists() {
    File file = new File("database");
    if (!file.exists()) return;  //not ready
    String data[][];
    SQL sql = new SQL();
    if (!sql.init()) {
//      setStatus("SQL connection failed");
      return;
    }
    data = sql.select("select name from lists");
    if (data == null) {
//      setStatus("select failed");
      return;
    }
    int yc = data.length;
    if (yc == 0) {
      //???
    }
    ArrayList<String> al = new ArrayList<String>();
    String e;
    for(int y=0;y<yc;y++) {
      e = data[y][0];
      al.add(e);
    }
    selected_list.setModel(new DefaultComboBoxModel(al.toArray()));
//    selectedList.setSelectedIndex(0);
    updateList();
  }

  private String getid(SQL sql, String sel) {
    String data[][];
    data = sql.select("select id from lists where name='" + sel +"'");
    if (data == null) {
//      setStatus("select failed");
      return null;
    }
    int yc = data.length;
    if (yc != 1) return null;
    return data[0][0];
  }

  public void importList() {
    String sel = (String)selected_list.getSelectedItem();
    if (sel == null || sel.length() == 0) return;
    JFileChooser chooser = new JFileChooser();
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    chooser.setMultiSelectionEnabled(false);
    chooser.setCurrentDirectory(new File(JF.getCurrentPath()));
    if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
    String num;
    SQL sql = new SQL();
    if (!sql.init()) {
      setStatus("SQL connection failed");
      return;
    }
    int line = 1;
    int errcnt = 0;
    int okcnt = 0;
    try {
      String id = getid(sql, sel);
      if (id == null) throw new Exception("unable to find list");
      BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(chooser.getSelectedFile().toString())));
      do {
        num = reader.readLine();
        if (num == null) break;
        int idx2 = num.indexOf(",");
        if (idx2 != -1) {
          num = num.substring(0, idx2);
        }
        if (!sql.execute("insert into listdata (id, number) values (" + id + ",'" + num.trim() + "')")) {
          errcnt++;
        } else {
          okcnt++;
        }
        line++;
      } while (true);
      reader.close();
    } catch (Exception e) {
      setStatus(e.toString());
      updateList();
      return;
    }
    setStatus("OK : File loaded : Inserted = " + okcnt + " : Errors = " + errcnt);
    updateList();
  }

  public void exportList() {
    String data[][];
    String sel = (String)selected_list.getSelectedItem();
    if (sel == null || sel.length() == 0) return;
    JFileChooser chooser = new JFileChooser();
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    chooser.setMultiSelectionEnabled(false);
    chooser.setCurrentDirectory(new File(JF.getCurrentPath()));
    if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) return;
    String num;
    SQL sql = new SQL();
    if (!sql.init()) {
      setStatus("SQL connection failed");
      return;
    }
    data = sql.select("select number,status,attempts,survey from listdata where id=(select id from lists where name='" + sel + "')");
    if (data == null) {
      setStatus("select failed (1)");
      return;
    }
    try {
      FileOutputStream fos = new FileOutputStream(chooser.getSelectedFile().toString());
      for(int a=0;a<data.length;a++) {
        fos.write((data[a][0] + "," + data[a][1] + "," + data[a][2] + "," + data[a][3] + "\r\n").getBytes());
      }
      fos.close();
    } catch (Exception e) {
      setStatus(e.toString());
      return;
    }
    setStatus("OK : List exported");
  }

  public void updateList() {
    String data[][];
    String sel = (String)selected_list.getSelectedItem();
    if (sel == null || sel.length() == 0) return;
    SQL sql = new SQL();
    if (!sql.init()) {
//      setStatus("SQL connection failed");
      return;
    }
    data = sql.select("select number, status, attempts, survey from listdata where id=(select id from lists where name='" + sel + "')");
    if (data == null) {
//      setStatus("updateList:select failed(1) : " + sql.lasterror);
      return;
    }
    listView.setModel(new DefaultTableModel(data, new String[] {"Number","Status","Attempts","Survey"}));
  }

  public boolean isConfigValid() {
    if (xfer_digit.getText().length() != 1) {setStatus("Error:Transfer digit is invalid"); return false;}
    for(int a=0;a<NUMQUESTIONS;a++) {
      if (questions.action[a] == A_GOTOUSER) {
        for(int b=0;b<9;b++) {
          if (questions.gotouser[a][b] != 0) break;
          if (b==8) {
            setStatus("Error:Question #" + (a+1) + " has an undefined goto action.");
            return false;
          }
        }
      }
      if (questions.action[a] == A_GOTOIDX) {
        if (questions.gotoidx[a] == 0) {
          setStatus("Error:Question #" + (a+1) + " has an undefined goto action.");
          return false;
        }
      }
    }
    if (sip_host.getText().length() == 0) {
      setStatus("Error:SIP host undefined.");
      return false;
    }
    if (sip_user.getText().length() == 0) {
      setStatus("Error:SIP user undefined.");
      return false;
    }
    int cnt = 0;
    try {
      for(int a=0;a<NUMQUESTIONS;a++) {
        if (!questions.enabled[a]) continue;
        File test = new File(questions.wav[a]);
        if (!test.exists()) {
          setStatus("Error : Message #" + (a+1) + " WAV file doesn't exist.");
          return false;
        }
        cnt++;
      }
    } catch (Exception e) {
      setStatus("Error:" + e);
      return false;
    }
    if (cnt == 0) {
      setStatus("Error:No messages defined.");
      return false;
    }
    cnt = 0;
    if (enable_g729a.isSelected()) cnt++;
    if (enable_g711u.isSelected()) cnt++;
    if (enable_g711a.isSelected()) cnt++;
    if (cnt == 0) {
      setStatus("Error:Must enable at least one codec");
      return false;
    }
    return true;
  }

  public static class Settings implements Serializable {
    static final long serialVersionUID = 1000L;
    String sql_host, sql_user, sql_pass;  //obsolete (do not delete or old cfg will not load)
    String sip_user, sip_auth, sip_host, sip_pass;
    String wav_filename;  //obsolete
    int numberLines = 16;
    String xfer;
    boolean disable_g729a;  //obsolete
    int delay = 100;
    boolean enable_xfer = false;
    char xfer_digit = '0';
    int maxRingTime = 60;  //in seconds
    int maxAttempts = 16;
    boolean disable_detect = false;
    boolean enable_g729a = true, enable_g711u = true, enable_g711a = false;
    boolean enable_reinvites = true;
    boolean check_update = true;
    int greetingThreshold = 1000, silenceThreshold = 1000, silenceDuration = 1000;
  }

  private Settings settings;

  public final void loadSetup() {
    try {
      FileInputStream fis = new FileInputStream("broadcast.cfg");
      ObjectInputStream ois = new ObjectInputStream(fis);
      settings = (Settings)ois.readObject();
      fis.close();

      sip_user.setText(settings.sip_user);
      sip_auth.setText(settings.sip_auth);
      sip_host.setText(settings.sip_host);
      sip_pass.setText(settings.sip_pass);
      number_lines.setValue(new Integer(settings.numberLines));
      xfer_number.setText(settings.xfer);
      disable_detect.setSelected(settings.disable_detect);
      if (settings.delay == 0) settings.delay = 100;
      delay.setValue(new Integer(settings.delay));
      enable_xfer.setSelected(settings.enable_xfer);
      xfer_digit.setText("" + settings.xfer_digit);
      if (settings.maxRingTime == 0) settings.maxRingTime = 60;
      maxRingTime.setValue(new Integer(settings.maxRingTime));
      if (settings.maxAttempts == 0) settings.maxAttempts = 16;
      maxAttempts.setValue(new Integer(settings.maxAttempts));

      enable_g729a.setSelected(settings.enable_g729a);
      enable_g711u.setSelected(settings.enable_g711u);
      enable_g711a.setSelected(settings.enable_g711a);
      enable_reinvites.setSelected(settings.enable_reinvites);
      check_update.setSelected(settings.check_update);

      greeting_threshold.setText(Integer.toString(settings.greetingThreshold));
      silence_threshold.setText(Integer.toString(settings.silenceThreshold));
      silence_duration.setText(Integer.toString(settings.silenceDuration));

      fis = new FileInputStream("broadcast-msgs.cfg");
      ois = new ObjectInputStream(fis);
      questions = (Questions)ois.readObject();

      fis.close();
    } catch (FileNotFoundException e) {
      loadDefaults();
      setStatus("Loading default settings");
      JFLog.log("No config found");
    } catch (Exception e) {
      loadDefaults();
      setStatus("Load Settings Failed:" + e);
      JFLog.log(e);
    }
    validateOptions();
  }

  private void loadDefaults() {
    settings = new Settings();
    number_lines.setValue(new Integer(16));
    delay.setValue(new Integer(100));
    maxRingTime.setValue(new Integer(60));
    maxAttempts.setValue(new Integer(16));
    greeting_threshold.setText("1000");
    silence_threshold.setText("1000");
    silence_duration.setText("1000");
  }

  private void validateOptions() {
    if ((Integer)number_lines.getValue() < 1) {
      number_lines.setValue(new Integer(1));
    }

    if ((Integer)delay.getValue() < 100) {
      delay.setValue(new Integer(100));
    }
    if ((Integer)delay.getValue() > 10000) {
      delay.setValue(new Integer(10000));
    }

    if ((Integer)maxRingTime.getValue() < 10) {
      maxRingTime.setValue(new Integer(10));
    }
    if ((Integer)maxRingTime.getValue() > 100) {
      maxRingTime.setValue(new Integer(100));
    }

    if ((Integer)maxAttempts.getValue() < 1) {
      maxAttempts.setValue(new Integer(1));
    }
    if ((Integer)maxAttempts.getValue() > 100) {
      maxAttempts.setValue(new Integer(100));
    }
    int value = JF.atoi(greeting_threshold.getText());
    if (value < 100 || value > 32000) greeting_threshold.setText("1000");
    value = JF.atoi(silence_threshold.getText());
    if (value < 100 || value > 32000) silence_threshold.setText("1000");
    value = JF.atoi(silence_duration.getText());
    if (value < 100 || value > 5000) silence_duration.setText("1000");
  }

  public void saveSetup() {
    validateOptions();
    saveQuestion();
    try {
      FileOutputStream fos = new FileOutputStream("broadcast.cfg");
      ObjectOutputStream oos = new ObjectOutputStream(fos);
      settings = new Settings();
      settings.sip_user = sip_user.getText();
      settings.sip_auth = sip_auth.getText();
      settings.sip_host = sip_host.getText();
      settings.sip_pass = sip_pass.getText();
      settings.wav_filename = "";  //obsolete
      settings.numberLines = (Integer)(number_lines.getValue());
      settings.xfer = xfer_number.getText();
      settings.disable_detect = disable_detect.isSelected();
      settings.delay = (Integer)(delay.getValue());
      settings.enable_xfer = enable_xfer.isSelected();
      settings.xfer_digit = xfer_digit.getText().charAt(0);
      settings.maxRingTime = (Integer)(maxRingTime.getValue());
      settings.maxAttempts = (Integer)(maxAttempts.getValue());
      settings.enable_g729a = enable_g729a.isSelected();
      settings.enable_g711u = enable_g711u.isSelected();
      settings.enable_g711a = enable_g711a.isSelected();
      settings.enable_reinvites = enable_reinvites.isSelected();
      settings.check_update = check_update.isSelected();
      oos.writeObject(settings);
      fos.close();
      fos = new FileOutputStream("broadcast-msgs.cfg");
      oos = new ObjectOutputStream(fos);
      oos.writeObject(questions);
      fos.close();
    } catch (Exception e) {
      setStatus("Save Settings Failed:" + e);
      JFLog.log(e);
      return;
    }
    setStatus("OK : saved");
  }

  public int localsipport = 5061;

  public int getlocalsipport() {
    int ret = localsipport;
    localsipport++;
    if (localsipport == 6000) localsipport = 5061;
    return ret;
  }

  public String getHost(String host) {
    int idx = host.indexOf(":");
    if (idx == -1) return host;
    return host.substring(0, idx);
  }

  public int getPort(String host, int def) {
    int idx = host.indexOf(":");
    if (idx == -1) return def;
    return Integer.valueOf(host.substring(idx+1));
  }

  public static class Lines {
    boolean inuse = false;  //this line in use?
    boolean ringing = false;  //is line ringing
    boolean talking = false;  //are we talking to someone on a line
    boolean xfered = false;  //was call transfered
    boolean hello = false;  //did we hear something on the line
    boolean repeat = false;  //repeating message
    String number;  //number we called
    String callid;  //not caller id, but a unique ID for this call leg
    String survey;  //user responses (long responses are in brackets)
    String multi;  //for long inputs
    RTP rtp;
    int msgidx = 0;
    int wavpos = 0;
    int ringwait = 0;
    int postwait = 0;
    int quietcount = 0;  //wait till we hear quiet after hello (answering machine detection)
  }

  public void startCalling() {
    if (!isConfigValid()) return;
    String sel = (String)selected_list.getSelectedItem();
    if (sel == null || sel.length() == 0) {
      setStatus("Pick a valid list(1)");
      return;
    }
    saveSetup();
    skipCount = 0;
    maxquietcount = settings.silenceDuration / 20;
    //lock resources
    setState(false);
    if (sip_pass.getText().length() == 0)
      setStatus("waiting for register");
    else
      setStatus("calling");

    JFLog.log("thresholds : " + settings.greetingThreshold + "," + settings.silenceThreshold + "," + settings.silenceDuration);
    fixList(true);

    //load WAV file(s)
    wav = new Wav[NUMQUESTIONS];
    int cnt = 0;
    for(int a=0;a<NUMQUESTIONS;a++) {
      wav[a] = new Wav();
      if (!questions.enabled[a]) continue;
      if (!wav[a].load(questions.wav[a])) {
        setStatus(wav[a].errmsg);
        setState(true);
        return;
      }
      cnt++;
    }

    if (cnt == 0) {
      setStatus("no messages");
      setState(true);
      return;
    }

    //create persistant sql connection
    psql = new SQL();
    if (!psql.init()) {
      setStatus("SQL connection failed");
      setState(true);
      return;
    }

    listid = getid(psql, sel);
    if (listid == null) {
      setStatus("Error : Pick a valid list");
      psql.uninit();
      setState(true);
      return;
    }

    state = states.CALLING;
    start.setText("Stop");
    //create SIP resources
    lineCount = (Integer)number_lines.getValue();
    sip = new SIPClient();
    sip.init(getHost(sip_host.getText()), getPort(sip_host.getText(), 5060), getlocalsipport(), this, SIP.Transport.UDP);
    if (sip_pass.getText().length() > 0) {
      sip.register(sip_user.getText(), sip_auth.getText(), sip_pass.getText());
      registered = false;
    } else {
      registered = true;
    }
    lines = new Lines[lineCount];
    for(int a=0;a<lineCount;a++) {
      lines[a] = new Lines();
    }
    //create 20ms timer
    java.util.Timer timer = new java.util.Timer();
    timer.scheduleAtFixedRate(new TimerTask() {
      public void run() {
        process();
      }
    }, 0, 20);

    int delayms = (Integer)delay.getValue();

    while (state == states.CALLING) {
      //look for a free SIP resource and fill it with a call
      JF.sleep(delayms);
      processUpdateList();
      String number = nextAvailableNumber();  //NOTE:this keeps sql connection established (keep alive)
      if (!registered) continue;
      if (number == null) {
        //no more numbers to dial
        if (anyStillCalling()) continue;
        setStatus("Finished list");
        break;
      }
      for(int a=0;a<lineCount;a++) {
        if (lines[a].inuse) continue;
        lines[a].rtp = null;
        lines[a].msgidx = 0;
        lines[a].wavpos = 0;
        lines[a].ringwait = 0;
        lines[a].postwait = 0;
        lines[a].xfered = false;
        lines[a].hello = false;
        lines[a].repeat = false;
        lines[a].number = number;
        lines[a].quietcount = 0;
        lines[a].survey = "";
        lines[a].multi = "";
        lines[a].inuse = true;
        lines[a].callid = dialNumber(number, lines[a]);
        markCalling(number);
        break;
      }
    }
    while (anyStillCalling()) {
      processUpdateList();
      JF.sleep(1000);  //wait for all calls to finish
    }
    processUpdateList();
    psql.uninit();
    timer.cancel();
    //unlock resources
    setState(true);
    if (state == states.STOPPING) {
      setStatus("stopped");
    }
    state = states.STOPPED;
    start.setText("Start!");
  }

  public void stopCalling() {
    state = states.STOPPING;
    setStatus("stopping");
  }

  public void forceStopCalling() {
    setStatus("killing connections");
    for(int a=0;a<lines.length;a++) {
      if (lines[a].inuse) {
        sip.bye(lines[a].callid);
        endCall(lines[a], "err_force_stop");
      }
    }
  }

  public void setState(boolean state) {
    sip_host.setEnabled(state);
    sip_auth.setEnabled(state);
    sip_user.setEnabled(state);
    sip_pass.setEnabled(state);
    save_setup.setEnabled(state);
    create_list.setEnabled(state);
    delete_list.setEnabled(state);
    selected_list.setEnabled(state);
    import_list.setEnabled(state);
    number_lines.setEnabled(state);
    xfer_number.setEnabled(state);
    reset_list.setEnabled(state);
    list_name.setEnabled(state);
    enable_g729a.setEnabled(state);
    enable_g711u.setEnabled(state);
    enable_g711a.setEnabled(state);
    enable_reinvites.setEnabled(state);
    disable_detect.setEnabled(state);
    export_list.setEnabled(state);
    delay.setEnabled(state);
    enable_xfer.setEnabled(state);
    xfer_digit.setEnabled(state);
    fix_list.setEnabled(state);
    enable.setEnabled(state);
    wav_filename.setEnabled(state);
    select_file.setEnabled(state);
    prev_msg.setEnabled(state);
    next_msg.setEnabled(state);
    single.setEnabled(state);
    multi.setEnabled(state);
    count.setEnabled(state);
    cont.setEnabled(state);
    terminate.setEnabled(state);
    gotouser.setEnabled(state);
    gotoidx.setEnabled(state);
    gotoidxnum.setEnabled(state);
    goto_1.setEnabled(state);
    goto_2.setEnabled(state);
    goto_3.setEnabled(state);
    goto_4.setEnabled(state);
    goto_5.setEnabled(state);
    goto_6.setEnabled(state);
    goto_7.setEnabled(state);
    goto_8.setEnabled(state);
    goto_9.setEnabled(state);
    maxRingTime.setEnabled(state);
    maxAttempts.setEnabled(state);
    xfer.setEnabled(state);
  }

  public String nextAvailableNumber() {
    String data[][];
    String sel = (String)selected_list.getSelectedItem();
    if (sel == null || sel.length() == 0) return null;
    //select next available number where status='new' or 'busy'.  order by status desc to get 'new' before 'busy'
    data = psql.select("select number from listdata where (status = 'new' or status = 'busy') and attempts < " + settings.maxAttempts + " and id=" + listid + " order by status desc, attempts asc fetch first row only");
    if (data == null) {
      setStatus("nextAvailableNumber : select failed (1)");
      return null;
    }
    if (data.length == 0) return null;
    return data[0][0];
  }

  public Codec[] getCodecs() {
    Codec codecs[] = new Codec[0];
    if (enable_g729a.isSelected()) codecs = SIP.addCodec(codecs, RTP.CODEC_G729a);
    if (enable_g711u.isSelected()) codecs = SIP.addCodec(codecs, RTP.CODEC_G711u);
    if (enable_g711a.isSelected()) codecs = SIP.addCodec(codecs, RTP.CODEC_G711a);
    return codecs;
  }

  public String dialNumber(String number, Lines line) {
    //generate a callid and initiate a sip call
    line.rtp = new RTP();
    line.rtp.init(this);
    SDP sdp = new SDP();
    SDP.Stream astream = sdp.addStream(SDP.Type.audio);
    astream.port = line.rtp.getlocalrtpport();
    astream.codecs = getCodecs();
    return sip.invite(number, sdp);
  }

  public void markCalling(String number) {
    String data[][];
    //set status='calling' and increment attempts
    String sel = (String)selected_list.getSelectedItem();
    if (sel == null || sel.length() == 0) return;
    int attempts = 0;
    data = psql.select("select attempts from listdata where number = '" + number + "' and id=" + listid);
    if (data == null) {
      setStatus("select failed");
      return;
    }
    if (data.length == 0) return;
    attempts = Integer.valueOf(data[0][0]) + 1;
    if (!psql.execute("update listdata set attempts = " + attempts + ", status = 'calling' where number = '" + number + "' and id=" + listid)) {
      setStatus("update failed");
      return;
    }
    //update local copy
    int rc = listView.getRowCount();
    for(int row=0;row<rc;row++) {
      if (((String)listView.getValueAt(row, 0)).equals(number)) {
        listView.setValueAt("calling", row, 1);
        listView.setValueAt(new Integer(attempts), row, 2);
        listView.repaint();
        return;
      }
    }
  }

  public void unmarkCalling() {
    String sel = (String)selected_list.getSelectedItem();
    if (sel == null || sel.length() == 0) return;
    if (!psql.execute("update lists set status = 'aborted' where status = 'calling' and id=" + listid)) {
      setStatus("update failed");
      return;
    }
    updateList();
  }

  public boolean anyStillCalling() {
    String data[][];
    String sel = (String)selected_list.getSelectedItem();
    if (sel == null || sel.length() == 0) return false;
    data = psql.select("select count(number) from listdata where status = 'calling' and id=" + listid);
    if (data == null) {
      setStatus("select failed");
      return false;
    }
    if (data.length == 0) return false;
    return !(data[0][0].equals("0"));
  }

  public void endCall(Lines line, String status) {
    System.out.println("endCall:" + line.number + ":status=" + status);
    line.talking = false;
    line.rtp.stop();
    line.rtp.uninit();
    line.rtp = null;
    line.callid = null;
    line.inuse = false;
    updateList.add(new update(line.number, status, line.survey));
  }

  public void processUpdateList() {
    String sel = (String)selected_list.getSelectedItem();
    if (sel == null || sel.length() == 0) return;
    update u;
    while (updateList.size() > 0) {
      u = updateList.remove(0);
      if (!psql.execute("update listdata set status = '" + u.status + "', survey = '" + u.survey + "' where number = '" + u.number + "' and id=" + listid)) {
        setStatus("endCall : update failed : " + u.number);
        return;
      }
      //update local copy
      int rc = listView.getRowCount();
      for(int row=0;row<rc;row++) {
        if (((String)listView.getValueAt(row, 0)).equals(u.number)) {
          listView.setValueAt(u.status, row, 1);
          listView.setValueAt(u.survey, row, 3);
          listView.repaint();
          break;
        }
      }
    }
  }

  public void process() {
    //20ms audio timer
    byte encoded[];
    if (processing) {
      skipCount++;
      setStatus("audio timer skipped : system too slow : reduce # of lines : skipCount=" + skipCount);
      return;
    }
    processing = true;
    try {
      for(int a=0;a<lineCount;a++) {
        if (!lines[a].inuse) continue;
        if (!lines[a].talking) {
          lines[a].ringwait++;
          if (lines[a].ringwait == 50 * settings.maxRingTime) {  //there are 50 process() per second
            //waiting/ringing for too long (1min)
            sip.cancel(lines[a].callid);
            endCall(lines[a], "no_anwser");
          }
          continue;
        }
        if (lines[a].quietcount < maxquietcount) {
          if (!lines[a].hello) {
            //detect hello/answering machine
            if (lines[a].rtp.getDefaultChannel().getSamples(tmp)) {
              for(int p=0;p<160;p++) {
                if (Math.abs(tmp[p]) > settings.greetingThreshold) {
                  lines[a].hello = true;
                  break;
                }
              }
            }
          } else {
            //detect end of hello/answering machine beep
            if (lines[a].rtp.getDefaultChannel().getSamples(tmp)) {
              int avg = 0;
              for(int p=0;p<160;p++) {
                avg += Math.abs(tmp[p]);
              }
              avg /= 160;
              if (avg > settings.silenceThreshold) {
                lines[a].quietcount = 0;
              } else {
                lines[a].quietcount++;
              }
            } else {
              lines[a].quietcount++;    //g729a silence suppression (evil)
            }
          }
          encoded = lines[a].rtp.getDefaultChannel().coder.encode(silence);
          lines[a].rtp.getDefaultChannel().writeRTP(encoded, 0, encoded.length);
        } else {
          if (lines[a].wavpos >= wav[lines[a].msgidx].samples.length) {
            if (questions.action[lines[a].msgidx] == A_CONT) {
              nextMessage(lines[a]);
              continue;
            }
            if (questions.action[lines[a].msgidx] == A_GOTOIDX) {
              lines[a].msgidx = questions.gotoidx[lines[a].msgidx] - 1 - 1;
              nextMessage(lines[a]);
              continue;
            }
            if (questions.action[lines[a].msgidx] == A_XFER) {
              if (lines[a].xfered) continue;  //already tried to xfer call
              if (xfer_number.getText().length() == 0) continue;  //no # to transfer to
              sip.refer(lines[a].callid, xfer_number.getText());
              lines[a].xfered = true;
              continue;
            }
            lines[a].postwait += 160;
            if (lines[a].postwait == 40000) {  //5 seconds
              if ((questions.action[lines[a].msgidx] == A_TERMINATE) || (questions.action[lines[a].msgidx] == A_XFER)) {
                sip.bye(lines[a].callid);
                endCall(lines[a], "ok");
                continue;
              } else {
                if ((questions.action[lines[a].msgidx] == A_MULTI) && (lines[a].multi.length() > 0)) {
                  lines[a].survey += "(" + lines[a].multi + ")";
                  nextMessage(lines[a]);
                } else {
                  //repeat message
                  lines[a].repeat = true;  //allow immediate response
                  lines[a].wavpos = 0;
                  lines[a].postwait = 0;
                  lines[a].multi = "";
                }
              }
            }
            encoded = lines[a].rtp.getDefaultChannel().coder.encode(silence);
            lines[a].rtp.getDefaultChannel().writeRTP(encoded, 0, encoded.length);
          } else {
            encoded = lines[a].rtp.getDefaultChannel().coder.encode(Arrays.copyOfRange(wav[lines[a].msgidx].samples, lines[a].wavpos, lines[a].wavpos + 160));
            lines[a].rtp.getDefaultChannel().writeRTP(encoded, 0, encoded.length);
            lines[a].wavpos += 160;
          }
        }
      }
    } catch (Exception e) {
      JFLog.log("process() exception:");
      JFLog.log(e);
    }
    processing = false;
  }

  public void checkVersion() {
    try {
      BufferedReader reader = new BufferedReader(new InputStreamReader(
        new URL("http://jfbroadcast.sourceforge.net/version.php").openStream()));
      String line = reader.readLine();
      if (line.equals(version)) {JFLog.log("version is up-to-date"); return;}
      JFLog.log("newer version is available : " + line);
      JOptionPane.showMessageDialog(this,
        "A newer version of jfbroadcast is available! (v" + line + ")\r\nPlease goto http://jfbroadcast.sourceforge.net to download it",
        "Info",
        JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
      JFLog.log("error while checking for version update");
      JFLog.log(e);
    }
  }

  //SIPClientInterface

  public void onRegister(SIPClient sip, boolean status) {
    if (status) {
      if (state != states.CALLING) return;
      registered = true;
      setStatus("calling");
    } else {
      if (state != states.CALLING) return;
      setStatus("Error : register failed");
    }
  }

  public void onTrying(SIPClient sip, String callid) {
    if (state == states.STOPPED) return;
    for(int a=0;a<lineCount;a++) {
      if (!lines[a].inuse) continue;
      if (!lines[a].callid.equals(callid)) continue;
      JFLog.log("trying : " + lines[a].number);
    }
  }

  public void onRinging(SIPClient sip, String callid) {
    if (state == states.STOPPED) return;
    for(int a=0;a<lineCount;a++) {
      if (!lines[a].inuse) continue;
      if (!lines[a].callid.equals(callid)) continue;
      lines[a].ringing = true;
      JFLog.log("ringing : " + lines[a].number);
    }
  }

  public void onSuccess(SIPClient sip, String callid, SDP sdp, boolean complete) {
    if (!complete) return;  //not interested in 183 (ringback)
    if (state == states.STOPPED) return;
    SDP.Stream astream = sdp.getFirstAudioStream();
    if (astream == null) return;
    for(int a=0;a<lineCount;a++) {
      if (!lines[a].inuse) continue;
      if (!lines[a].callid.equals(callid)) continue;
      if (!lines[a].talking) {
        int cnt = 0;
        if (astream.hasCodec(RTP.CODEC_G729a)) cnt++;
        if (astream.hasCodec(RTP.CODEC_G711u)) cnt++;
        if (astream.hasCodec(RTP.CODEC_G711a)) cnt++;
        if ((cnt > 1) && (enable_reinvites.isSelected())) {
          Codec codecs[] = new Codec[0];
          //try to reinvite with one codec
          if (astream.hasCodec(RTP.CODEC_G729a)) {
            codecs = new Codec[] {RTP.CODEC_G729a};
          }
          else if (SIP.hasCodec(codecs, RTP.CODEC_G711u)) {
            codecs = new Codec[] {RTP.CODEC_G711u};
          }
          else if (SIP.hasCodec(codecs, RTP.CODEC_G711a)) {
            codecs = new Codec[] {RTP.CODEC_G711a};
          }
          SDP localsdp = new SDP();
          SDP.Stream localStream = localsdp.addStream(SDP.Type.audio);
          localStream.codecs = codecs;
          localStream.port = lines[a].rtp.getlocalrtpport();
JFLog.log("reinvite:" + lines[a].number);
          sip.reinvite(callid, localsdp);
          return;
        }
JFLog.log("connected : number=" + lines[a].number);
        lines[a].rtp.start();
        RTPChannel channel = lines[a].rtp.createChannel(astream);
        if (channel == null) {
          JFLog.log("Failed to create RTPChannel:" + lines[a].number);
          return;
        };
        channel.start();
        lines[a].ringing = false;
        if (settings.disable_detect) {
          lines[a].hello = true;
          lines[a].quietcount = maxquietcount;
        }
        lines[a].talking = true;
        return;
      }
    }
  }

  public void onBye(SIPClient sip, String callid) {
    if (state == states.STOPPED) return;
    for(int a=0;a<lineCount;a++ ){
      if (!lines[a].inuse) continue;
      if (lines[a].callid.equals(callid)) {
        endCall(lines[a], "ok");
      }
    }
  }

  public int onInvite(SIPClient sip, String callid, String fromid, String fromnumber, SDP sdp) {
    return 486;  //busy
  }

  public void onCancel(SIPClient sip, String callid, int code) {
    if (state == states.STOPPED) return;
    for(int a=0;a<lineCount;a++ ){
      if (!lines[a].inuse) continue;
      if (lines[a].callid.equals(callid)) {
        switch (code) {
          case 486: endCall(lines[a], "busy"); break;
          default: endCall(lines[a], "err_" + code); break;
        }
      }
    }
  }

  public void onRefer(SIPClient sip, String callid) {
    if (state == states.STOPPED) return;
    for(int a=0;a<lineCount;a++ ){
      if (!lines[a].inuse) continue;
      if (lines[a].callid.equals(callid)) {
        endCall(lines[a], "ok_xfered");
      }
    }
  }

  public void onNotify(SIPClient sip, String callid, String event, String content) {
  }

  //RTPInterface

  public void rtpSamples(RTPChannel rtp) {}

  public void rtpDigit(RTPChannel channel, char c) {
    if (state == states.STOPPED) return;
    if (c == '*') return;
    for(int a=0;a<lineCount;a++ ){
      if (!lines[a].inuse) continue;
      if (lines[a].rtp == channel.rtp) {
        if ((enable_xfer.isSelected()) && (c == xfer_digit.getText().charAt(0))) {
          if (lines[a].xfered) return;  //already tried to xfer call
          if (xfer_number.getText().length() == 0) return;
          sip.refer(lines[a].callid, xfer_number.getText());
          lines[a].xfered = true;
          return;
        }
        if ((lines[a].wavpos < 8000 * 5) && (!lines[a].repeat)) {
          return;  //too soon (msg must play at least 5 sec before response is allowed)
        }
        switch (questions.action[lines[a].msgidx]) {
          case A_TERMINATE:
            break;
          case A_SINGLE:
            lines[a].survey += c;
            nextMessage(lines[a]);
            break;
          case A_MULTI:
            if (c == '#') {
              lines[a].survey += "(" + lines[a].multi + ")";
              nextMessage(lines[a]);
            } else {
              lines[a].multi += c;
            }
            lines[a].postwait = 0;
            break;
          case A_GOTOUSER:
            if (c == '#') return;  //bad input
            if (c == '0') return;  //bad input
            int newidx = questions.gotouser[lines[a].msgidx][c - '0' - 1];
            if ((newidx < 1) || (newidx > 99)) return;  //bad input
            lines[a].msgidx = newidx - 1 - 1;  //-1 for zero based, -1 for nextMessage()
            nextMessage(lines[a]);
            break;
        }
      }
    }
  }

  public void rtpH263(RTPChannel rtp, byte[] bytes, int off, int len) {}
  public void rtpH263_1998(RTPChannel rtp, byte[] bytes, int off, int len) {}
  public void rtpH263_2000(RTPChannel rtp, byte[] bytes, int off, int len) {}
  public void rtpH264(RTPChannel rtp, byte[] bytes, int off, int len) {}
  public void rtpJPEG(RTPChannel rtp, byte[] bytes, int off, int len) {}
  public void rtpVP8(RTPChannel rtp, byte[] bytes, int off, int len) {}
  public void rtpInactive(RTPChannel rtp) {}

  private void nextMessage(Lines line) {
    line.wavpos = 0;
    line.postwait = 0;
    line.multi = "";
    line.repeat = false;
    while (true) {
      if (line.msgidx == NUMQUESTIONS-1) {
        sip.bye(line.callid);
        endCall(line, "ok");
        return;
      }
      line.msgidx++;
      if (line.msgidx < 0) continue;
//      System.out.println("nextMsg=" + line.msgidx);
      if (questions.enabled[line.msgidx]) return;
    }
  }

  public void rtpPacket(RTPChannel rtp, byte[] data,int pos,int len) {}
  public void rtcpPacket(RTPChannel rtp, byte[] data,int pos,int len) {}

  public static class Questions implements Serializable {
    static final long serialVersionUID = 1000L;
    boolean enabled[] = new boolean[NUMQUESTIONS];
    String wav[] = new String[NUMQUESTIONS];
    int action[] = new int[NUMQUESTIONS];
    int count[] = new int[NUMQUESTIONS];  //# digits allowed for single entry
    int gotouser[][] = new int[NUMQUESTIONS][9];
    int gotoidx[] = new int[NUMQUESTIONS];
    Questions() {
      for(int a=0;a<NUMQUESTIONS;a++) {
        enabled[a] = false;
        wav[a] = new String();
        action[a] = A_CONT;
        count[a] = 0;
      }
    }
  }

  public static Questions questions = new Questions();
  private int idx = 0;

  public void selectFile() {
    JFileChooser chooser = new JFileChooser();
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    chooser.setMultiSelectionEnabled(false);
    chooser.setCurrentDirectory(new File(JF.getCurrentPath()));
    if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
    wav_filename.setText(chooser.getSelectedFile().toString().replaceAll("\\\\", "/"));
  }

  private void prevQuestion() {
    if (idx == 0) return;
    saveQuestion();
    idx--;
    loadQuestion();
    try { msg_idx.setValue(idx); } catch (Exception e) {System.out.println("" + e);}
  }

  private void nextQuestion() {
    if (idx == NUMQUESTIONS-1) return;
    saveQuestion();
    idx++;
    loadQuestion();
    try { msg_idx.setValue(idx); } catch (Exception e) {System.out.println("" + e);}
  }

  private void gotoQuestion(int newidx) {
    saveQuestion();
    idx = newidx;
    loadQuestion();
  }

  private void loadQuestion() {
    title.setText("#" + (idx+1) + "/" + NUMQUESTIONS);
    enable.setSelected(questions.enabled[idx]);
    wav_filename.setText(questions.wav[idx]);
    cont.setSelected(questions.action[idx] == A_CONT);
    single.setSelected(questions.action[idx] == A_SINGLE);
    multi.setSelected(questions.action[idx] == A_MULTI);
    terminate.setSelected(questions.action[idx] == A_TERMINATE);
    gotouser.setSelected(questions.action[idx] == A_GOTOUSER);
    gotoidx.setSelected(questions.action[idx] == A_GOTOIDX);
    xfer.setSelected(questions.action[idx] == A_XFER);
    count.setSelectedIndex(questions.count[idx]);
    goto_1.setText("" + questions.gotouser[idx][0]);
    goto_2.setText("" + questions.gotouser[idx][1]);
    goto_3.setText("" + questions.gotouser[idx][2]);
    goto_4.setText("" + questions.gotouser[idx][3]);
    goto_5.setText("" + questions.gotouser[idx][4]);
    goto_6.setText("" + questions.gotouser[idx][5]);
    goto_7.setText("" + questions.gotouser[idx][6]);
    goto_8.setText("" + questions.gotouser[idx][7]);
    goto_9.setText("" + questions.gotouser[idx][8]);
    gotoidxnum.setText("" + questions.gotoidx[idx]);
  }

  private void saveQuestion() {
    questions.enabled[idx] = enable.isSelected();
    questions.wav[idx] = wav_filename.getText();
    if (cont.isSelected()) questions.action[idx] = A_CONT;
    if (single.isSelected()) questions.action[idx] = A_SINGLE;
    if (multi.isSelected()) questions.action[idx] = A_MULTI;
    if (terminate.isSelected()) questions.action[idx] = A_TERMINATE;
    if (gotouser.isSelected()) questions.action[idx] = A_GOTOUSER;
    if (gotoidx.isSelected()) questions.action[idx] = A_GOTOIDX;
    if (xfer.isSelected()) questions.action[idx] = A_XFER;
    questions.count[idx] = count.getSelectedIndex();
    questions.gotouser[idx][0] = Math.min(Math.abs(JF.atoi(goto_1.getText())), 99);
    questions.gotouser[idx][1] = Math.min(Math.abs(JF.atoi(goto_2.getText())), 99);
    questions.gotouser[idx][2] = Math.min(Math.abs(JF.atoi(goto_3.getText())), 99);
    questions.gotouser[idx][3] = Math.min(Math.abs(JF.atoi(goto_4.getText())), 99);
    questions.gotouser[idx][4] = Math.min(Math.abs(JF.atoi(goto_5.getText())), 99);
    questions.gotouser[idx][5] = Math.min(Math.abs(JF.atoi(goto_6.getText())), 99);
    questions.gotouser[idx][6] = Math.min(Math.abs(JF.atoi(goto_7.getText())), 99);
    questions.gotouser[idx][7] = Math.min(Math.abs(JF.atoi(goto_8.getText())), 99);
    questions.gotouser[idx][8] = Math.min(Math.abs(JF.atoi(goto_9.getText())), 99);
    questions.gotoidx[idx] = Math.min(Math.abs(JF.atoi(gotoidxnum.getText())), 99);
  }

  private void loadHelp(){
    try {
      FileInputStream fis = new FileInputStream("readme.txt");
      int len = fis.available();
      byte txt[] = new byte[len];
      fis.read(txt);
      help.setText(new String(txt,0,len));
      help.setCaretPosition(0);
    } catch (Exception e) { }
  }

  private void processArgs() {
    if (args == null || args.length == 0) return;
    for(int a=0;a<args.length;a++) {
      if (args[a].equals("-start")) {
        a++;
        if (a == args.length) {
          JFLog.log("Error:Must include list with -start option");
          return;
        }
        int cnt = selected_list.getItemCount();
        boolean ok = false;
        for(int b=0;b<cnt;b++) {
          String item = (String)selected_list.getItemAt(b);
          if (item.equals(args[a])) {
            selected_list.setSelectedIndex(b);
            start.doClick();
            ok = true;
            break;
          }
        }
        if (!ok) {
          JFLog.log("Error:specifed list for -start option not found");
        }
      }
    }
  }
  private void setPosition() {
    Dimension d = getSize();
    Rectangle s = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
    if ((d.width > s.width) || (d.height > s.height)) {
      if (d.width > s.width) d.width = s.width;
      if (d.height > s.height) d.height = s.height;
      setSize(d);
    }
    setLocation(s.width/2 - d.width/2, s.height/2 - d.height/2);
  }
}
