/**
 * Created : Mar 25, 2012
 *
 * @author pquiring
 */

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.io.*;

import javaforce.jna.*;
import javaforce.*;

public class MediaApp extends javax.swing.JFrame {

  /**
   * Creates new form MediaApp
   */
  public MediaApp() {
    initComponents();
    This = this;
    panel = new MainPanel();
    setContentPane(panel);
    setPosition();
    if (args.length > 0) {
      if (args[0].equals("--javavideo")) MainPanel.useVideoFrame = true;  //experimental
      File file = new File(args[0]);
      if (file.exists()) {
        panel.play(file);
      }
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jMedia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 952, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    if (!FFMPEG.init()) {
      if (!FFMPEG.download()) return;
      if (!FFMPEG.init()) return;  //try again after download
    }
    MediaApp.args = args;
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MediaApp().setVisible(true);
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

  public static javax.swing.JFrame This;
  public static String args[];
  public static MainPanel panel;

  private void setPosition() {
    Dimension d = getSize();
    Rectangle s = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
    if ((d.width > s.width) || (d.height > s.height)) {
      if (d.width > s.width) d.width = s.width;
      if (d.height > s.height) d.height = s.height;
      setSize(d);
    }
    setLocation(s.width/2 - d.width/2, s.height/2 - d.height/2);
  }
}
