#!/bin/bash
java -cp /usr/share/java/javaforce.jar:/usr/share/java/jna.jar:/usr/share/java/jna-platform.jar:/usr/share/java/jcifs.jar:/usr/share/java/jsch.jar:/usr/share/java/jzlib.jar:/usr/share/java/jfile.jar jfile.FileApp $*
