/**
 * Created : Feb 28, 2012
 *
 * @author pquiring
 */

import javax.swing.*;
import java.awt.*;

import javaforce.*;

public class RepoApp extends javax.swing.JFrame {

  /**
   * Creates new form RepoApp
   */
  public RepoApp() {
    JFLog.init(JF.getUserPath() + "/.jrepo.log", true);
    initComponents();
    JPanel panel = new MainPanel();
    this.setContentPane(panel);
/*
    Dimension size = panel.getPreferredSize();
    setVisible(true);
    Insets insets = this.getInsets();
    size.width += insets.left + insets.right;
    size.height += insets.top + insets.bottom;
    setSize(size);
*/
    this.setExtendedState(this.MAXIMIZED_BOTH);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jrepo");
        setName("frame");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    RepoApp.args = args;
    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new RepoApp().setVisible(true);
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

  public static String args[];
}
