/**
 * Created : Jun 8, 2012
 *
 * @author pquiring
 */

import java.awt.*;
import java.awt.event.*;

import javaforce.*;

public class PasswordsApp extends javax.swing.JFrame implements ActionListener {

  private String version = "0.10";

  /**
   * Creates new form PasswordsApp
   */
  public PasswordsApp() {
    initComponents();
    setTitle("jfPasswords/" + version);
    panel = new MainPanel();
    setContentPane(panel);
    setPosition();
    JFImage appicon = new JFImage();
    appicon.loadPNG(this.getClass().getClassLoader().getResourceAsStream("jpasswords.png"));
    setIconImage(appicon.getImage());
    JFImage scaled = new JFImage(16, 16);
    scaled.fill(0, 0, 16, 16, 0x00000000, true);  //fill with alpha transparent
    scaled.getGraphics().drawImage(appicon.getImage()
      , 0, 0, 15, 15
      , 0, 0, appicon.getWidth()-1, appicon.getHeight()-1, null);
    //create tray icon
    PopupMenu popup = new PopupMenu();
    show = new MenuItem("Show");
    show.addActionListener(this);
    popup.add(show);
    popup.addSeparator();
    exit = new MenuItem("Exit");
    exit.addActionListener(this);
    popup.add(exit);
    icon = new TrayIcon(scaled.getImage(), "Passwords", popup);
    icon.addActionListener(this);
    tray = SystemTray.getSystemTray();
    try { tray.add(icon); } catch (Exception e) { JFLog.log(e); }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setTitle("Passwords");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 763, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 534, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

  }//GEN-LAST:event_formWindowClosing

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new PasswordsApp().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  private void setPosition() {
    Dimension d = getSize();
    Rectangle s = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
    if ((d.width > s.width) || (d.height > s.height)) {
      if (d.width > s.width) d.width = s.width;
      if (d.height > s.height) d.height = s.height;
      setSize(d);
    }
    setLocation(s.width/2 - d.width/2, s.height/2 - d.height/2);
  }

  public void actionPerformed(ActionEvent e) {
    Object o = e.getSource();
    if (o == exit) {
      if (panel.dirty) {
        switch (JF.showConfirm3("Confirm", "Save first?")) {
          case JF.YES: panel.saveSafe(); break;
          case JF.NO: break;
          case JF.CANCEL: return;
        }
      }
      System.exit(0);
    }
    if (o == show) {
      if (isVisible()) {
        panel.checkTimestamp();
        if ((getExtendedState() & Frame.ICONIFIED) == Frame.ICONIFIED) {
          setExtendedState(getExtendedState() ^ Frame.ICONIFIED);
        }
        requestFocus();
        return;
      }
      if (MainPanel.config.reAuthOnShow && (MainPanel.password != null)) {
        String password = GetPassword.getPassword(this);
        if (password == null) return;
        if (!password.equals(MainPanel.password)) {
          JF.showMessage("Error", "Wrong Password");
          return;
        }
      }
      panel.checkTimestamp();
      setVisible(true);
    }
  }

  private MainPanel panel;
  public SystemTray tray;
  public TrayIcon icon;
  public MenuItem exit, show;
}
