#!/bin/sh

### BEGIN INIT INFO
# Provides:          jlogond
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start jlogon daemon
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/bin/true
PIDDIR=/dev/null
JLOGONDPID=$PIDDIR/jlogond.pid

# clear conflicting settings from the environment
unset TMPDIR

# See if the daemon is there
test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Starting jlogon" "jlogon"

#		start-stop-daemon --start --quiet --oknodo --exec $DAEMON -- $JQEMUD_OPTS
    jlogon &

		log_end_msg $?
		;;

	stop)
		log_daemon_msg "Stopping jlogon" "jlogon"
#		start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
		log_end_msg $?
		;;

	restart|force-reload)
#		$0 stop && sleep 2 && $0 start
		;;

	status)
#		status_of_proc -p $JLOGONDPID $DAEMON jqemu && exit 0 || exit $?
		echo Okay
		;;
	*)
		echo "Usage: /etc/init.d/jlogond {start|stop|restart|force-reload|status}"
		exit 1
		;;
esac
